- Jenkinsfile
- Source/FPGA Addon FPGA IP.lvproj
- Source/FPGA Addon SysDef API.lvproj
- Source/FPGA Addon.lvproj
- build.toml
Updated lvproj build file paths by removing the "Custom Devices" folder from the path as it causes duplicates in the install path.
Added all build specifications the build.toml file.
Updated jenkinsfile as currently it uses 'vs-common-build' library instead of 'vs-build-tools'
Currently, the build fails on the Jenkins machine without executing any of the build steps.
n/a
> Updated build spec paths, build.toml and Jenkinsfile

- Jenkinsfile
There was a misplaced apostrophe in the Jenkinsfile which made the build to fail instantly.
The build is failing due to the typo in the Jenkinsfile.
n/a
> Fixed the apostrophe type in Jenkinsfile

- Jenkinsfile
Moved the diffPipeline step back to its previous location (before the build execute command)
Currently the diff step is executed after the build step. 
Run in a replay and this modification did not cause any trouble in the build process.
> Moved the diffPipeline step back to its previous location (before the build execute command)

- control
- Update the package name to match conventions used by officially supported custom devices
- Update the EULA to be the NI default
- Set the architecture to be windows_x64 (see [here](https://dev.azure.com/ni/DevCentral/_workitems/edit/1037130))
- Add VeriStand as a dependency
The architecture fix is required to pass internal package validation rules. The other two items bring the package in-line with other custom devices.
N/A
> Update package name, architecture, license

- Source/Addon/Custom Device FPGA Addon.xml
Currently the FPGA Addon Custom Device appears outside(under) the National Instruments right click menu, which appears when trying to add a new custom device in the System Explorer. This PR fixes this issue.
Currently the FPGA Addon Custom Device appears outside(under) the National Instruments right click menu, which appears when trying to add a new custom device in the System Explorer. 
Built the CD locally, and verified if the fix actually fixed the issue in the System Explorer.
> FPGA Addon now appears under the National Instruments menu, in System Explorer

- Source/Addon/Custom Device FPGA Addon.xml
This pull request fixes a bug which caused NI VeriStand System Explorer to enter in a frozen state. 
Currently when deleting Scalars or Waveforms using the Delete Multiple Items option from the tree, the System Explorer enters an unresponsive state and must be closed through task manager. This issue was caused the "Delete multiple items" right-click menu option when it was called in certain pages. The problem was caused by the fact that the Scalar or Waveforms pages are not refreshed when using that delete option from the tree. In order to avoid this showstopper,  the option was removed from several pages and it was left in only Parent elements in the System explorer->FPGA Addon tree such as: Scalar, Waveform; and remove from child elements such as Scalar Inputs, Scalar Outputs, Waveform …
> Fixed VS freeze bug by leaving the "Delete Multiple Items" options only on tree options not requiring implicit page refresh 

- Source/FPGA Addon System Definition API.lvproj
This PR changes the build location of the System Definition API build spec (FPGA Addon System Definition API.lvproj) from Built\Custom Devices\FPGA Addon\Windows\System Definition API to Built\Custom Device\FPGA Addon\Windows\System Definition API
The built System Definition API lands in the incorrect location when building it.
Changed the path and built the build specification in order to make sure that the files end up in the right location.
> Removed the Custom Device folder from the built path

- .gitmodules
This pull request changes the source of the FPGA Addon Speciality IO submodule from 
"https://github.com/DStavilaNI/FPGA-Addon-Speciality-IO/tree/5662f422962b30ccd0df3cebbb989a27bcc8d829" to "https://github.com/ni/niveristand-fpga-addon-speciality-io"
Currently the submodule is pulled in from a fork not from the official ni repository.
Updated the .gitmodules file and synced the submodules locally by calling the "git submodules --init --recursive" command. Also opened the FPGA Addon.lvproj to make sure that the project is able to find the dependencies synced from the new location and that no VIs and SubVIs are borken.
> Modified the .gitmodules file so not it pulls the FPGA Addon Speciality IO from niveristand-fpga-addon-speciality-io repo

- control
Fixes the issue where the suggested items list (installer) displays the "FPGA Addon for VeriStand 2020" instead of "NI FPGA Addon for VeriStand 2020"
The installer name is displayed incorrectly in the suggested items list
N/a. Can be tested once the new installers are built
> Fixed naming issue in suggested items list (NI FPGA Addon for VeriStand {year})

- control
A bug was discovered while testing where the version number of the FPGA Addon entry contains the package version number as well. This shouldn't be the case. This PR fixes the bug. 
Currently the version number of the FPGA Addon is displayed incorrectly in the Package Manager during the installation.
n/a. Can be tested once the feed installer gets built.
> Fixed the issue regarding the incorrect FPGA Addon version number

- build.toml
This request changes the order in which the components of the nipkg files are built. It makes the Scripting Examples to be built after the Scripting API buildspec was built.
The Scripting Examples project is dependent on the Scripting API, so building it before building the Scripting API results in build error.
n/a
> Fixed the build error where the Scripting Examples were built before the Scripting API

- Source/Addon/Addon System Explorer/FPGA Addon System Explorer.lvlib
In PR 85 a bug was introduced. The "Set Scalar Channel Data.vi" was renamed to "Get Item Data.vi" but the FPGA Addon System Explorer.lvlib was not saved. This PR fixes the issue.
Currently several project components are broken and the automated build system is also failing.
Build the Configuration release locally and it passed. A build on the PR will also be performed.
> Added the file which was renamed but after that the FPGA Addon System Explorer.lvlib was not save

- Source/Tests/System Tests/Bitfile Reload Testing/Assets/test_Bitfile Reload_Scalar Data Type Change FXP/Example SysDef.nivssdf
- Source/Tests/System Tests/Bitfile Reload Testing/Assets/test_Bitfile Reload_Scalar Data Type Change SGL/Example SysDef.nivssdf
- 
Provides a fix for the failing Bitfile Reload System Level tests. In the system definition provided as tests asset the RIO address of the FPGA board the bitfile should run on is set to RIO0 however, the in the test devices the correct address if RIO1.
Without these modifications the Bitfile Reload System Level tests will keep failing.
Investigated the issue on the test machine. Run the tests manually with the updated RIO address and they all passed.
> Changed the RIO address off the FPGA Addon CD from RIO0 to RIO1

- build.toml
Updates build.toml to fix failing build. Failure was caused by a missing lvproj, which was removed intentionally in a previous PR.
Old project that required a build step was removed, thus fixing the CD build.
N/A
> Update build.toml by removing old API project

- Source/FPGA Addon.lvproj
- Added a "Bundled Dependencies" virtual folder for Windows and PharLap targets in order to fix namespace issues.
- To allow other custom devices that use similar dependencies with different versions to deploy and run together inside the same system definition.
- Deployed the built engine with a similar fix for a Linux64 cRIO to make sure everything works as expected inside VeriStand.
> Dependencies namespace for Windows and PharLap targets

- Source/Tests/Unit Tests/FPGA Register IO Testing/FPGA Register IO Tests/targets.ini
Replaces the IP address in the target.ini file with the IP address of the target used for ATS runs.
With the current IP Address ATS tests will likely fail once the NIR target is not available.
n/a
> Fixed the incorrect controller address in the target.ini file

- Source/FPGA Addon.lvproj
This pull request removes a file from the LabVIEW project as it causes the Jenkins build to fail. Please note that the file was removed from the physical folder with PR110 (https://github.com/ni/niveristand-fpga-addon-custom-device/pull/110)
but it was left in the FPGA Addon.lvproj and this caused the Jenkins build to fail with missing file error.
The Jenkins build is failing due to the missing file.
Built the Configuration Build build specification after the file was removed from the project and it passed successfully.
> Removed the image046.jpg from the LabVIEW project

- build.toml
Changes the Scripting API example project name from "FPGA Addon Scripting Examples.lvproj" to "FPGA Addon Scripting API Examples.lvproj" in the build.toml file.
The changes which caused the build failure was introduced in PR #110.
The build is currently failing because the "FPGA Addon Scripting Examples.lvproj" name is no longer valid and it can't be located by the build machine.
N/A
> Added the correct example project name into the build.toml file

- Source/Tests/System Tests/Scalar Channels Testing/Assets/VS FPGA Addon Scalar Testing/VS FPGA Addon Scalar Testing.nivssdf
Fixes an error which was introduce with PR #107. The issue was that due to incorrectly built CD RT Drivers for the ARM and Linux X64 Targets, the system definition was saved with incorrect paths to the RT Drivers.
Due to the issue generated by the incorrect RT Driver paths all Linux X64 tests are failing on the ATS Machine.
Run the tests locally and they all passed. 
Validated the paths manually on the development machine.
> Remade the system definition which had the incorrect paths to the RT Drivers

- Source/Addon/Support Files/Help/HTML Help Source/Main.html
TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).
Corrects the misleading information in the Main.html file which says that only specific FXP types are supported.
The information about the FXP support is misleading and incorrect in the Main.html page.
Opened the HTML file to see if it's rendered correctly.
> Updated the Main.html as it still contains information about the old supported FXP configuration

- Source/FPGA Addon.lvproj
- Adds two virtual folders for each Target in the LabVIEW project:
- NI VeriStand APIs - that contains the VeriStand APIs
- Bundled Dependencies - that contains shared dependencies
- This change is required in order to fix namespace issues with other Custom Devices during deployment.
- The Custom Device has been built using LabVIEW 2019 and deployed on a clean Virtual Machine with VeriStand 2019 R3 in order to validate that OPAL-RT Power Electronics Addon and FPGA Addon can deploy successfully on a PharLap Target. 
NI VeriStand APIs settings:
Bundled Dependencies settings:
> Bundle shared dependencies in order to fix namespace issues with other Custom Devices

- Source/Addon/Custom Device FPGA Addon.xml
Make the custom device appear under the "NI" menu item, rather than "National Instruments".
Branding update.
N/A
> Parent custom device under NI in menu

- Jenkinsfile
- Source/Addon/Custom Device FPGA Addon.xml
- Source/FPGA Addon.lvproj
- Builds the custom device for 2019 and 2020 32-bit and 2021 64-bit
- Removes Pharlap and Linux ARM support
The custom device will need to be built for 2021 64-bit to support VeriStand 2021.
Manually built the custom device according to the build.toml order for 2021 64-bit.
Copied the built exports to a 2021 test machine and ran all tests:
LabVIEW 2021 throws `Error 1026: Reference is invalid` when closing empty references, and this was an issue in the VI below:
`Source\Tests\Unit Tests\DMA Channels Testing\DMA Channel Testing\private\CD Storage Library Unload.vi`
After removing the caller of that VI (which [doesn't seem](https://github.com/ni/niveristand-fpga-addon-custom-device/pull/40) to support 2021 out of the box), I re-ran the tests and saw only one failure (also due to LV 2021's …
> Enable building for 2021 64-bit

- Jenkinsfile
- build.toml
- control_scripting_api
- control_scripting_examples
Support installing packages dependent on LabVIEW 2021 by targeting the correct bitness and package name.
Fix duplicated package name string between examples and scripting packages.
Fix ATS execution by allowing 2021 scripting support to be installed.
Verified packages built and installed on both LV 2020 32-bit and 2021 64-bit.
Verified examples could be run in 2021.
> Support installing packages dependent on LabVIEW 2021

- Source/Addon/Custom Device FPGA Addon.xml
Remove all target support except for Windows and Linux x64
Fix #149 
Validated in VS 2020 R6 that creating a new instance of the CD does not show dependent file errors in System Explorer.
> Update target support in Custom Device XML

- control
TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-fpga-addon-custom-device/blob/master/CONTRIBUTING.md).
TODO: Include high-level description of the changes in this pull request.
As part of User Story (https://ni.visualstudio.com/DevCentral/_workitems/edit/2665528/) We are trying to include localization description for Chinese, German, Japanese, French, Korean languages for different VeriStand third party products.
TODO: Justify why this contribution should be part of the project.
Taken reference from VeriStand control page (‪\argo\ni\nipkg\pool\ni-v\ni-veristand-2024\24.0.0\24.0.0.49451-0+f299\ni-veristand-2024_24.0.0.49451-0+f299_windows_x64.nipkg.control) and edited niveristand-fpga-addon-custom-device control …
> Adding localization text in niveristand-fpga-addon-custom-device control page in six different languages
